CREATE TABLE formulas(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    subtema VARCHAR(255) NOT NULL,
    tema VARCHAR(255) NOT NULL,
    tags VARCHAR(255) NOT NULL,
    texto TEXT CHARACTER SET utf8 NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE usuarios
(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(25) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	fechaRegistro DATETIME NOT NULL,
	activo TINYINT NOT NULL,
	PRIMARY KEY(id)
);